Feature/refactor model
tlab-pss/PersonalDataRepository pull request #4
Opened 2019-09-25 09:49 UTC by yuuis

2019-09-25 10:04 UTC, sskmy1024y requested changes
とりあえず動作確認しようか

2019-09-25 10:04 UTC, sskmy1024y commented on models/location/location.go
> +	Latitude       string
DBにstringで持たせるのはいいんだけど、内部的に全部をstringで持たせるのは違う気がする‥…

2019-09-25 15:21 UTC, yuuis commented on models/location/location.go
> +	Latitude       string
大丈夫そうだから、floatにしたよー

2019-09-25 15:21 UTC, yuuis commented
どうかくOKです！

2019-09-27 02:28 UTC, sskmy1024y reviewed
pendingのままだった

2019-09-27 02:28 UTC, sskmy1024y commented on models/location/location.go
> +	Latitude       string
DBにstringで持たせるのはいいんだけど、内部的に全部をstringで持たせるのは違う気がする‥…

2019-09-27 02:30 UTC, sskmy1024y commented
![LGTM](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

2019-09-27 02:43 UTC, sskmy1024y reviewed
ちょっと気になったことコメントした〜〜

2019-09-27 02:43 UTC, sskmy1024y commented on models/registration_information/registration_infomation.go
> +package registration_information
`registration_information` って名詞名詞になってるの変な感じする。
`register_infomation` とか？ 気にならなかったらいいと思う。

2019-09-27 02:43 UTC, sskmy1024y commented on api/controllers/locations_controller.go
> +	Longitude      float64 `json:"longitude"`
:+1:

2019-09-27 02:43 UTC, sskmy1024y commented on models/location/location.go
> +	Transportation string
そもそもの話になっちゃってごめんなんだけど、

| MySQL | NoSQL |
| ----- | ----- |
| 確定情報 | 推測情報 |

って感じだったよね？（違ったらごめん）

その形で行くなら`Location` の情報って確定情報（推測ではない情報）だからMySQLに入れるけど、`Transportation`ってユーザーからの進言がない限り推測情報に部類されるから、NoSQLに入れることになる……？

2019-09-27 03:50 UTC, yuuis commented on models/location/location.go
> +	Transportation string
確かに、推測情報(特にレコメンドシステムで推測されたやつ)はmysqlに入れたくないけど、じゃあ移動手段はどこに入れるか？ってなると難しいよね。

nosqlに移動手段だけのドキュメントを作ってもいいけど、情報の場所として、緯度経度と使う場面がほぼ同じだと考えられるから、ここでもいいような気がする...

どうするのがいいと思う？

2019-09-27 03:53 UTC, yuuis commented on models/registration_information/registration_infomation.go
> +package registration_information
んー
好みかなーと思ったけど、登録された(ている)情報だから`registered_information` にしてみた

2019-09-27 11:41 UTC, sskmy1024y commented on models/location/location.go
> +	Transportation string
こういうの、要素増やしていけばいくほどいっぱい出てきそう……

そもそもMySQLとNoSQLと分ける理由はなんだっけ？どっちもNoSQLじゃダメなの？

2019-09-27 16:05 UTC, yuuis commented on models/location/location.go
> +	Transportation string
MySQLとmongoを分ける理由は、ユーザにまつわる構造の変わらないデータと構造の変わりやすいデータ(= サービスのプラグインとかで構造の変わるような推測データ)を分けるためだね。

確かに今は分ける意味がないから全部mongoに入れてもいいかもしれない。

2019-09-27 16:07 UTC, yuuis commented on models/location/location.go
> +	Transportation string
全部mongoにしても、結局はどっちのコレクション(確定情報コレクションか、推測情報コレクションか)に入れるかでこういう話にはなりそうな気がする(小声)

2019-09-28 17:10 UTC, yuuis commented
全部mongoにしたよー
apiは変わらないけど、リファクタでめっちゃでかいPRになっちゃった。ごめん。

2019-09-29 01:06 UTC, sskmy1024y reviewed
mongo置き換え自体は一通り見たよ〜

2019-09-29 01:06 UTC, sskmy1024y commented on api/controllers/basics_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
`NotFoundError` なら 404でいい気がする

2019-09-29 01:06 UTC, sskmy1024y commented on api/controllers/basics_controller.go
>  		Mail:      ipt.Mail,
**今回のPRじゃなくていいけど**、Mailは `SNS` とか `Contacts` っていうカテゴリの中に入れて、TwitterとかLINEとかFacebookとかのアカウント連携とかと同じテーブルの方がいい気がした。

2019-09-29 01:06 UTC, sskmy1024y commented on api/controllers/health_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
ここも

2019-09-29 01:06 UTC, sskmy1024y commented on api/controllers/locations_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
ここも

2019-09-29 01:06 UTC, sskmy1024y commented on api/controllers/registered_information_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
ここもか

2019-09-29 01:06 UTC, sskmy1024y commented on infrastructures/mongo.go
> +	client, err := mongo.NewClient(options.Client().ApplyURI("mongodb://user:password@mongo:27017/pss"))
ここのuser:passwordとかって環境変数化しなくていいの？

2019-09-29 01:06 UTC, sskmy1024y commented on db/mongo/init/createUser.js
> +    pwd: 'password',
ここのuser:passwordとかって環境変数にしなくていいの？

2019-09-29 01:06 UTC, sskmy1024y commented on api/controllers/basics_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
あ〜、なるほど。DB側がNot Foundを返してるけど、URLが存在しないわけじゃないから `NoContent`にしてるのか……。

2019-09-29 01:06 UTC, sskmy1024y commented on models/location/location.go
> +	Transportation string
そうなんだよね……
やっぱり今見てても、`Transportation` を`Latitude`とかと一緒の扱いにするのはどうなんだって思ってしまった……。今使ってるウイルスアプリだって、位置情報を送るネイティブプラグインが勝手に推測して乗り物を送ってくれてるだけだし

2019-09-29 01:45 UTC, yuuis commented on api/controllers/basics_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
そーそー。
200で空配列を返すのと迷ったけど、ステータスコードで表現できるカッコ良さに惹かれて204にした。

2019-09-29 01:52 UTC, yuuis commented on api/controllers/basics_controller.go
>  		Mail:      ipt.Mail,
おけ。必要になったら対応しよう。

2019-09-29 02:03 UTC, yuuis commented on infrastructures/mongo.go
> +	client, err := mongo.NewClient(options.Client().ApplyURI("mongodb://user:password@mongo:27017/pss"))
手抜きがばれた
環境変数にしたよー

2019-09-29 02:05 UTC, yuuis commented on db/mongo/init/createUser.js
> +    pwd: 'password',
jsで環境変数とるのめんどくさそうだったから手抜きした..
ここはいいかなって

2019-09-29 02:07 UTC, sskmy1024y commented on api/controllers/basics_controller.go
> +			presenters.ViewNoContent(ctx) // TODO: noContent返していいのか？
まあとりあえずええんじゃなかろか。

2019-09-29 02:08 UTC, yuuis reviewed
んーめんどくさいから、一旦`transportation`消したわ。

必須の情報ではないし、位置情報と時間さえあれば(たぶん)復元できるし、後から考えてもよさそう

2019-09-29 02:08 UTC, sskmy1024y commented on db/mongo/init/createUser.js
> +    pwd: 'password',
たしかにSSRするわけじゃなかったら面倒そう

2019-09-29 02:12 UTC, sskmy1024y approved these changes
LGTM！
![](http://livedoor.blogimg.jp/bluesignal/imgs/9/5/95d3a71e.jpg)

2019-09-29 02:21 UTC, merged